//! Section layout — port of `build_map.py` / `pipeline.js` map building:
//! group by section, order sections along a 1-D PCA of their centroids, arrange
//! them on a grid, and lay each section's sounds out in a unit box by a local
//! 2-D projection. (First pass uses PCA-2D on the CLAP embeddings; the
//! similarity-preserving upgrade — UMAP/neighbor embedding — is M4 proper.)

use std::collections::{BTreeMap, HashMap};

/// World-space node radius (shared with the renderer for sizing + hit-testing).
pub const NODE_R: f32 = 1.6;

/// One analyzed sound, pre-layout.
pub struct Analyzed {
    pub path: String,
    pub filename: String,
    pub section: String,
    pub confidence: f32,
    pub embedding: Vec<f32>, // L2-normalized CLAP embedding
    pub envelope: Vec<f32>,  // peak-amplitude bars, drives the playback waveform
    pub duration: f32,       // seconds, for the waveform playhead
}

/// One laid-out node ready to render.
#[derive(Clone)]
pub struct Node {
    pub path: String,
    pub filename: String,
    pub section: String,
    pub confidence: f32,
    pub x: f32,
    pub y: f32,
    pub color: [f32; 3],
    pub rel_x: f32,
    pub rel_y: f32,
    pub section_id: u32,
    pub envelope: Vec<f32>,
    pub duration: f32,
    /// Spring target for the force sim. Equals the laid-out position until a
    /// drag re-anchors it (a valid drop makes where-you-dropped-it the new
    /// home; an invalid one leaves it alone so the node springs back).
    pub home_x: f32,
    pub home_y: f32,
    /// Force-sim velocity.
    pub vx: f32,
    pub vy: f32,
}

/// Stable small id per section name (used by the shader to test "same section
/// as hovered" for the highlight/dim/gradient effect). Public so the legend
/// (screen-space UI, computed outside this module) can drive the same highlight.
pub fn section_id(section: &str) -> u32 {
    use std::hash::{Hash, Hasher};
    let mut h = std::collections::hash_map::DefaultHasher::new();
    section.hash(&mut h);
    h.finish() as u32
}

pub struct SectionMeta {
    pub name: String,
    pub count: usize,
    pub color: [f32; 3],
    pub cx: f32,
    pub cy: f32,
}

/// Section → hex color (same palette as pipeline.js), fallback grey.
/// Section palette, generated by farthest-point sampling in CIE-Lab so no two
/// categories read as the same colour (min pairwise Lab distance 28.3; the old
/// hand-picked palette had many near-duplicate pairs — Kick/808/Crash all red,
/// Rimshot/Ride both green, Closed Hat/Cymbal both orange, ...).
/// Kick/Open Hat/Clap/Closed Hat/Rimshot are pinned to their drum-convention
/// hues; the rest were filled in to maximize separation from those anchors.
fn section_hex(section: &str) -> &'static str {
    match section {
        "Kick" => "#ff5e62",
        "808" => "#e23abb",
        "Bass" => "#b4d570",
        "Snare" => "#3ad2e2",
        "Rimshot" => "#20bf6b",
        "Clap" => "#4b7bec",
        "Snap" => "#e23a7d",
        "Closed Hat" => "#fd9644",
        "Open Hat" => "#fed330",
        "Ride" => "#c982ed",
        "Crash" => "#aa6040",
        "Cymbal" => "#aa3ae2",
        "Tom" => "#d7ca97",
        "Conga" => "#92cd1d",
        "Cowbell" => "#e689b1",
        "Shaker" => "#b59734",
        "Tambourine" => "#3ae24b",
        "Woodblock" => "#97b7d7",
        "Rolls" => "#d7a097",
        "Vocal" => "#79cca3",
        // Deliberately low-chroma: the "don't know" pile shouldn't dominate.
        "Unsorted" => "#7079b8",
        _ => "#888888",
    }
}

fn hex_to_rgb(hex: &str) -> [f32; 3] {
    let h = hex.trim_start_matches('#');
    let p = |i: usize| u8::from_str_radix(&h[i..i + 2], 16).unwrap_or(136) as f32 / 255.0;
    [p(0), p(2), p(4)]
}

pub fn color_for(section: &str) -> [f32; 3] {
    hex_to_rgb(section_hex(section))
}

/// Collision relaxation: push apart any two nodes closer than `min_dist`.
/// ponytail: O(n²·iters) per section — fine for typical section sizes (hundreds);
/// a spatial grid would be needed if a single section held many thousands.
fn relax_nodes(off: &mut [[f32; 2]], min_dist: f32) {
    let n = off.len();
    if n < 2 {
        return;
    }
    let iters = if n > 400 { 24 } else { 60 };
    for _ in 0..iters {
        for i in 0..n {
            for j in (i + 1)..n {
                let dx = off[j][0] - off[i][0];
                let dy = off[j][1] - off[i][1];
                let d2 = dx * dx + dy * dy;
                if d2 < min_dist * min_dist {
                    let d = d2.sqrt();
                    // Coincident points: separate along a per-index direction.
                    let (ux, uy) = if d > 1e-4 {
                        (dx / d, dy / d)
                    } else {
                        let a = (i * 977 + j) as f32;
                        (a.cos(), a.sin())
                    };
                    let push = (min_dist - d.max(0.0)) * 0.5;
                    off[i][0] -= ux * push;
                    off[i][1] -= uy * push;
                    off[j][0] += ux * push;
                    off[j][1] += uy * push;
                }
            }
        }
    }
}

/// Section centers: seed the blobs in a sunflower spiral (compact, no grid, not
/// by similarity) then relax so no two blobs (radius = `radii[i]`) overlap.
fn arrange_sections(radii: &[f32]) -> Vec<[f32; 2]> {
    let n = radii.len();
    if n == 1 {
        return vec![[0.0, 0.0]];
    }
    // Seed by CUMULATIVE AREA, biggest blob at the centre. The old seed used
    // `avg_r * sqrt(i)`, which ignores how unequal the sections really are
    // (thousands of snares vs a few dozen rolls), so large blobs started deep
    // inside each other and relaxation had to untangle them from scratch.
    let golden = 2.399_963_2_f32; // golden angle
    let mut order: Vec<usize> = (0..n).collect();
    order.sort_by(|&a, &b| radii[b].total_cmp(&radii[a]));
    let mut pos = vec![[0.0f32, 0.0]; n];
    let mut area = 0.0f32;
    for (k, &i) in order.iter().enumerate() {
        // Radius enclosing everything placed so far (loosened for packing
        // inefficiency) so each new blob lands outside its predecessors.
        let r = (area / std::f32::consts::PI).sqrt() * 1.15;
        let a = k as f32 * golden;
        pos[i] = [r * a.cos(), r * a.sin()];
        area += std::f32::consts::PI * (radii[i] + SECTION_MARGIN).powi(2);
    }

    // Relax, stopping as soon as it's clean rather than always burning 200 passes.
    for _ in 0..300 {
        let mut worst = 0.0f32;
        for i in 0..n {
            for j in (i + 1)..n {
                let dx = pos[j][0] - pos[i][0];
                let dy = pos[j][1] - pos[i][1];
                let mut d = (dx * dx + dy * dy).sqrt();
                let min_d = radii[i] + radii[j] + SECTION_MARGIN;
                if d < min_d {
                    worst = worst.max(min_d - d);
                    if d < 1e-4 {
                        d = 1e-4;
                    }
                    let push = (min_d - d) * 0.5;
                    let (ux, uy) = (dx / d, dy / d);
                    pos[i][0] -= ux * push;
                    pos[i][1] -= uy * push;
                    pos[j][0] += ux * push;
                    pos[j][1] += uy * push;
                }
            }
        }
        if worst <= 1e-3 {
            break;
        }
    }

    // Guarantee, not a hope. Pairwise relaxation can stall — a blob pinned
    // between neighbours gets pushed back as fast as it's pushed out — so it
    // can exit still overlapping. Scaling every position about the origin
    // scales every pairwise distance by exactly the same factor, so applying
    // the single worst violation ratio separates ALL pairs at once. This is a
    // no-op (s == 1) whenever relaxation already converged.
    let mut s = 1.0f32;
    for i in 0..n {
        for j in (i + 1)..n {
            let dx = pos[j][0] - pos[i][0];
            let dy = pos[j][1] - pos[i][1];
            let d = (dx * dx + dy * dy).sqrt().max(1e-4);
            s = s.max((radii[i] + radii[j] + SECTION_MARGIN) / d);
        }
    }
    if s > 1.0 {
        for p in &mut pos {
            p[0] *= s;
            p[1] *= s;
        }
    }
    pos
}

/// Gap between category blobs, in world units. Deliberately just over one node
/// diameter: enough that the boundary between two categories reads, but small
/// enough that the map stays ONE segregated mass instead of islands floating in
/// dead space. Widening this makes the map look more scattered, not more
/// organised — the cohesion comes from dense blobs (see PACK_BASE), not gaps.
const SECTION_MARGIN: f32 = NODE_R * 2.2;

#[cfg(test)]
mod tests {
    use super::*;

    /// No two category blobs may overlap — including the pathological shapes
    /// the real corpus produces (one huge class, many tiny ones).
    #[test]
    fn sections_never_overlap() {
        let cases: Vec<Vec<f32>> = vec![
            vec![120.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0],       // one giant + dust
            vec![50.0; 21],                                   // all equal
            vec![1.0, 2.0, 3.0, 80.0, 5.0, 90.0, 2.5, 40.0],  // mixed
            vec![7.0, 7.0],                                   // minimum case
            (1..=20).map(|i| i as f32 * 6.0).collect(),        // linear ramp
        ];
        for radii in cases {
            let pos = arrange_sections(&radii);
            for i in 0..radii.len() {
                for j in (i + 1)..radii.len() {
                    let dx = pos[j][0] - pos[i][0];
                    let dy = pos[j][1] - pos[i][1];
                    let d = (dx * dx + dy * dy).sqrt();
                    let need = radii[i] + radii[j] + SECTION_MARGIN;
                    assert!(
                        d >= need - 1e-2,
                        "overlap: r={radii:?} pair {i},{j} d={d} need={need}"
                    );
                }
            }
        }
    }
}

/// Local 2-D layout in the unit box: PCA init + UMAP-style neighbour embedding,
/// so nearby points on screen are genuinely nearby in CLAP space (the colour
/// gradient reads `rel_x`/`rel_y` straight off this).
/// `pca_only` returns the raw PCA projection instead — kept so the layout_check
/// bin can measure how much the neighbour embedding actually buys us.
pub fn local_layout_2d_opt(embeddings: &[Vec<f32>], pca_only: bool) -> Vec<[f32; 2]> {
    let n = embeddings.len();
    if n == 1 {
        return vec![[0.5, 0.5]];
    }
    if n <= 6 {
        // Too few points for a meaningful neighbour graph. Pack them as a
        // compact sunflower disc — the old version placed them on a ring of
        // fixed radius, which rendered small categories as literal hollow
        // circles and made the map look like scattered confetti.
        return (0..n)
            .map(|i| {
                let a = i as f32 * 2.399_963;
                let r = 0.5 * ((i as f32 + 0.5) / n as f32).sqrt();
                [0.5 + r * a.cos(), 0.5 + r * a.sin()]
            })
            .collect();
    }
    let dim = embeddings[0].len();
    let mut mean = vec![0f32; dim];
    for v in embeddings {
        for i in 0..dim {
            mean[i] += v[i] / n as f32;
        }
    }
    let mut std = vec![0f32; dim];
    for v in embeddings {
        for i in 0..dim {
            let d = v[i] - mean[i];
            std[i] += d * d;
        }
    }
    for s in &mut std {
        *s = (*s / n as f32).sqrt();
        if *s < 1e-6 {
            *s = 1.0;
        }
    }
    let centered: Vec<Vec<f32>> = embeddings
        .iter()
        .map(|v| (0..dim).map(|i| (v[i] - mean[i]) / std[i]).collect())
        .collect();

    let power = |mat: &[Vec<f32>]| -> Vec<f32> {
        let mut u = vec![0f32; dim];
        for i in 0..dim {
            u[i] = ((i * 40503) & 0xffff) as f32 / 65535.0 - 0.5;
        }
        for _ in 0..16 {
            let mut nu = vec![0f32; dim];
            for c in mat {
                let dot: f32 = c.iter().zip(&u).map(|(a, b)| a * b).sum();
                for i in 0..dim {
                    nu[i] += c[i] * dot;
                }
            }
            let norm = nu.iter().map(|x| x * x).sum::<f32>().sqrt().max(1e-9);
            for x in &mut nu {
                *x /= norm;
            }
            u = nu;
        }
        u
    };

    let u1 = power(&centered);
    let deflated: Vec<Vec<f32>> = centered
        .iter()
        .map(|c| {
            let proj: f32 = c.iter().zip(&u1).map(|(a, b)| a * b).sum();
            (0..dim).map(|i| c[i] - proj * u1[i]).collect()
        })
        .collect();
    let u2 = power(&deflated);

    let proj: Vec<[f32; 2]> = centered
        .iter()
        .map(|c| {
            let p1 = c.iter().zip(&u1).map(|(a, b)| a * b).sum();
            let p2 = c.iter().zip(&u2).map(|(a, b)| a * b).sum();
            [p1, p2]
        })
        .collect();

    // PCA is only the INITIALIZATION. Within one class the embeddings form a
    // tight cluster, so the top-2 principal components are mostly noise — using
    // them as the final layout is why the colour gradient looked random. The
    // neighbour embedding below is what actually preserves similarity.
    let init = unit_box(&proj);
    if pca_only {
        return init;
    }
    let knn = knn_graph(&centered, K_NEIGHBORS.min(n - 1));
    unit_box(&umap_sgd(&knn, init, SGD_EPOCHS))
}

fn local_layout_2d(embeddings: &[Vec<f32>]) -> Vec<[f32; 2]> {
    local_layout_2d_opt(embeddings, false)
}

/// Initial per-section box size, as a multiple of `sqrt(n) * min_dist` (the
/// natural packed side). Seeding much smaller forces `relax_nodes` to expand the
/// whole blob, and that global rearrangement wrecks the similarity structure the
/// neighbour embedding just produced. Measured k-NN recall of the ON-SCREEN
/// coordinates vs this constant (ceiling is 47.0%, the unrelaxed layout):
///   0.286 (the old `1.2*sqrt(n)`) → 16.9%   0.55 → 41.4%
///   0.70  → 44.6%                            0.85 → 46.0%
/// Higher preserves more structure but spreads each blob out. At 0.70 the gaps
/// between nodes were wide enough that a category read as loose confetti rather
/// than a single mass, so this is deliberately back near snug packing: visual
/// grouping is the whole point of the map, and it's worth a few points of recall.
const PACK_BASE: f32 = 0.48;
const K_NEIGHBORS: usize = 15;
const SGD_EPOCHS: usize = 300;
const N_NEGATIVE: usize = 5;
// UMAP's default curve fit for min_dist=0.1, spread=1.0. `b` is specialised to
// 1.0 in the SGD (see the force loops) to avoid two powf() per force, which
// dominated layout time; only `a` is still referenced.
const UMAP_A: f32 = 1.577;

/// Min-max each axis into the unit box.
fn unit_box(p: &[[f32; 2]]) -> Vec<[f32; 2]> {
    let (mut minx, mut maxx, mut miny, mut maxy) = (f32::MAX, f32::MIN, f32::MAX, f32::MIN);
    for q in p {
        minx = minx.min(q[0]);
        maxx = maxx.max(q[0]);
        miny = miny.min(q[1]);
        maxy = maxy.max(q[1]);
    }
    let sx = (maxx - minx).max(1e-6);
    let sy = (maxy - miny).max(1e-6);
    p.iter().map(|q| [(q[0] - minx) / sx, (q[1] - miny) / sy]).collect()
}

/// Brute-force k-nearest-neighbours by squared Euclidean distance.
/// ponytail: O(n²·d) per section. Fine at the few-hundred-per-section sizes a
/// sample folder produces; swap in HNSW if a single section ever gets huge.
fn knn_graph(x: &[Vec<f32>], k: usize) -> Vec<Vec<u32>> {
    let n = x.len();
    let row = |i: usize| -> Vec<u32> {
        let mut d: Vec<(f32, u32)> = (0..n)
            .filter(|&j| j != i)
            .map(|j| {
                let s = x[i].iter().zip(&x[j]).map(|(a, b)| (a - b) * (a - b)).sum::<f32>();
                (s, j as u32)
            })
            .collect();
        let nth = k.min(d.len()) - 1;
        d.select_nth_unstable_by(nth, |a, b| a.0.total_cmp(&b.0));
        d.truncate(k);
        d.into_iter().map(|(_, j)| j).collect()
    };

    // O(n²·512) and embarrassingly parallel — the single-threaded version was a
    // real chunk of the post-analysis stall on big sections.
    let threads = std::thread::available_parallelism().map(|p| p.get()).unwrap_or(4).min(n.max(1));
    if threads <= 1 || n < 256 {
        return (0..n).map(row).collect();
    }
    let chunk = n.div_ceil(threads);
    let mut out: Vec<Vec<u32>> = Vec::new();
    std::thread::scope(|s| {
        let handles: Vec<_> = (0..n)
            .step_by(chunk)
            .map(|start| {
                let row = &row;
                s.spawn(move || (start..(start + chunk).min(n)).map(row).collect::<Vec<_>>())
            })
            .collect();
        for h in handles {
            out.extend(h.join().unwrap_or_default());
        }
    });
    out
}

/// UMAP's SGD layout: attract k-NN pairs, repel negative samples. This is the
/// same optimizer the web app gets from umap-js — and the same force sim the
/// GPU "breathing" pass will later run continuously.
fn umap_sgd(knn: &[Vec<u32>], init: Vec<[f32; 2]>, epochs: usize) -> Vec<[f32; 2]> {
    let n_neg = N_NEGATIVE;
    let n = init.len();
    let mut pos = init;
    // Spread the PCA init out so points aren't all on top of each other.
    for p in &mut pos {
        p[0] *= 10.0;
        p[1] *= 10.0;
    }
    let mut rng: u32 = 42; // deterministic layout (mirrors the web app's seeded PRNG)
    let mut next = || {
        rng ^= rng << 13;
        rng ^= rng >> 17;
        rng ^= rng << 5;
        rng
    };
    let clamp = |v: f32| v.clamp(-4.0, 4.0);

    for e in 0..epochs {
        let alpha = 1.0 - e as f32 / epochs as f32; // linear learning-rate decay
        for i in 0..n {
            for &jj in &knn[i] {
                let j = jj as usize;
                // --- attraction along a k-NN edge ---
                let (dx, dy) = (pos[i][0] - pos[j][0], pos[i][1] - pos[j][1]);
                let d2 = dx * dx + dy * dy;
                if d2 > 0.0 {
                    // b == 1 specialisation: the general form needs two powf()
                    // per force, and those dominated layout time (285ms for a
                    // 220-node section). With b=1 the curve is
                    // 1/(1 + a*d2) and the powfs vanish.
                    let coef = -2.0 * UMAP_A / (1.0 + UMAP_A * d2);
                    pos[i][0] += clamp(coef * dx) * alpha;
                    pos[i][1] += clamp(coef * dy) * alpha;
                    pos[j][0] -= clamp(coef * dx) * alpha;
                    pos[j][1] -= clamp(coef * dy) * alpha;
                }
                // --- repulsion from N random negative samples ---
                for _ in 0..n_neg {
                    let k = (next() as usize) % n;
                    if k == i {
                        continue;
                    }
                    let (dx, dy) = (pos[i][0] - pos[k][0], pos[i][1] - pos[k][1]);
                    let d2 = dx * dx + dy * dy;
                    let coef = 2.0 / ((0.001 + d2) * (1.0 + UMAP_A * d2));
                    pos[i][0] += clamp(coef * dx) * alpha;
                    pos[i][1] += clamp(coef * dy) * alpha;
                }
            }
        }
    }
    pos
}

/// Canonical section order. Fixed (not discovery order) so a section's preview
/// slot never moves as new categories show up mid-analysis.
pub const SECTIONS: &[&str] = &[
    // Crash and Ride were merged into Cymbal: measured, the classifier predicted
    // Ride only 37% and Cymbal 2% of the time — those distinctions were fiction.
    "Kick", "808", "Bass", "Snare", "Rimshot", "Clap", "Snap", "Closed Hat", "Open Hat",
    "Cymbal", "Tom", "Conga", "Cowbell", "Shaker", "Tambourine",
    "Woodblock", "Rolls", "Vocal", "Unsorted",
];

/// Where a section's blob sits while analysis streams in. Phyllotaxis over the
/// canonical index, so it's stable from the first sound onward — the real
/// `build_map` layout replaces it once every sound is in.
pub fn section_slot(name: &str) -> [f32; 2] {
    let i = SECTIONS.iter().position(|&s| s == name).unwrap_or(SECTIONS.len() - 1) as f32;
    let a = i * 2.399963; // golden angle
    let r = 30.0 * (i + 0.5).sqrt();
    [r * a.cos(), r * a.sin()]
}

/// The exact within-section pipeline used by `build_map`: neighbour embedding,
/// then collision packing. Exposed so `layout_check` measures the coordinates
/// actually drawn (and coloured), not just the pre-relaxation layout.
pub fn packed_layout(embeddings: &[Vec<f32>]) -> Vec<[f32; 2]> {
    let min_dist = 2.0 * NODE_R + 1.0;
    let xy = local_layout_2d(embeddings);
    let base = PACK_BASE * (embeddings.len() as f32).sqrt() * min_dist;
    let mut off: Vec<[f32; 2]> =
        xy.iter().map(|p| [(p[0] - 0.5) * 2.0 * base, (p[1] - 0.5) * 2.0 * base]).collect();
    relax_nodes(&mut off, min_dist);
    off
}

/// One step of the force sim — a port of the web app's d3-force setup: a soft
/// spring pulling each node to its home, collision so nodes give way instead of
/// overlapping, velocity damping, and a cooling alpha so it settles.
///
/// `fixed` is the node being dragged (excluded from integration — the cursor
/// owns it). Collision uses a uniform grid: the old `relax_nodes` O(n²) is fine
/// once at layout time but would not hold up at 60fps.
pub fn physics_step(nodes: &mut [Node], alpha: f32, fixed: Option<usize>) {
    let n = nodes.len();
    if n == 0 {
        return;
    }
    // Params mirror app.js, which scaled them by node count.
    let big = n > 800;
    let spring = if big { 0.25 } else { 0.20 };
    let damp = if big { 0.70 } else { 0.64 }; // d3 stores 1 - velocityDecay
    let iters = if big { 1 } else { 2 };
    let collide_strength = if big { 0.45 } else { 0.7 };
    let min_dist = 2.0 * NODE_R + 1.0;

    // --- spring toward home ---
    for (i, nd) in nodes.iter_mut().enumerate() {
        if Some(i) == fixed {
            continue;
        }
        nd.vx += (nd.home_x - nd.x) * spring * alpha;
        nd.vy += (nd.home_y - nd.y) * spring * alpha;
    }

    // --- collision, over a uniform grid ---
    let cell = min_dist;
    // Reused across iterations: a fresh HashMap + a Vec per bucket every
    // iteration every frame was a steady allocation churn during analysis.
    let mut grid: HashMap<(i32, i32), Vec<usize>> = HashMap::with_capacity(n * 2);
    for _ in 0..iters {
        for v in grid.values_mut() {
            v.clear();
        }
        for (i, nd) in nodes.iter().enumerate() {
            grid.entry(((nd.x / cell) as i32, (nd.y / cell) as i32)).or_default().push(i);
        }
        for i in 0..n {
            let (cx, cy) = ((nodes[i].x / cell) as i32, (nodes[i].y / cell) as i32);
            for gx in cx - 1..=cx + 1 {
                for gy in cy - 1..=cy + 1 {
                    let Some(bucket) = grid.get(&(gx, gy)) else { continue };
                    for &j in bucket {
                        if j <= i {
                            continue;
                        }
                        let (dx, dy) = (nodes[j].x - nodes[i].x, nodes[j].y - nodes[i].y);
                        let d2 = dx * dx + dy * dy;
                        if d2 >= min_dist * min_dist || d2 <= 1e-9 {
                            continue;
                        }
                        let d = d2.sqrt();
                        let push = (min_dist - d) / d * collide_strength * 0.5;
                        let (ox, oy) = (dx * push, dy * push);
                        if Some(i) != fixed {
                            nodes[i].vx -= ox;
                            nodes[i].vy -= oy;
                        }
                        if Some(j) != fixed {
                            nodes[j].vx += ox;
                            nodes[j].vy += oy;
                        }
                    }
                }
            }
        }
    }

    // --- damp + integrate ---
    for (i, nd) in nodes.iter_mut().enumerate() {
        if Some(i) == fixed {
            nd.vx = 0.0;
            nd.vy = 0.0;
            continue;
        }
        nd.vx *= damp;
        nd.vy *= damp;
        nd.x += nd.vx;
        nd.y += nd.vy;
    }
}

/// Build the full map: section grid + per-section local layout. World Y grows
/// downward here (matches image/grid conventions); the renderer flips as needed.
pub fn build_map(items: Vec<Analyzed>) -> (Vec<Node>, Vec<SectionMeta>) {
    if items.is_empty() {
        return (vec![], vec![]);
    }
    // Group by section (BTreeMap for deterministic order pre-sort).
    let mut by_section: BTreeMap<String, Vec<Analyzed>> = BTreeMap::new();
    for it in items {
        by_section.entry(it.section.clone()).or_default().push(it);
    }

    let mut order: Vec<String> = by_section.keys().filter(|s| *s != "Unsorted").cloned().collect();
    if by_section.contains_key("Unsorted") {
        order.push("Unsorted".to_string());
    }

    // Per-section local layouts. Nodes ("planets") start compact so collision
    // packs them into a tight cluster rather than a sparse cloud — the initial
    // box is deliberately small (< the natural packed radius) so relaxation
    // pulls the blob together to a uniform min-distance packing.
    let min_dist = 2.0 * NODE_R + 1.0;
    let mut sec_off: Vec<Vec<[f32; 2]>> = Vec::new();
    let mut sec_rel: Vec<Vec<[f32; 2]>> = Vec::new();
    let mut radii: Vec<f32> = Vec::new();
    for sec in &order {
        let items = &by_section[sec];
        let embs: Vec<Vec<f32>> = items.iter().map(|it| it.embedding.clone()).collect();
        let xy = local_layout_2d(&embs); // unit box
        let base = PACK_BASE * (items.len() as f32).sqrt() * min_dist;
        let mut off: Vec<[f32; 2]> =
            xy.iter().map(|p| [(p[0] - 0.5) * 2.0 * base, (p[1] - 0.5) * 2.0 * base]).collect();
        relax_nodes(&mut off, min_dist);
        let (mx, my) = (
            off.iter().map(|o| o[0]).sum::<f32>() / off.len() as f32,
            off.iter().map(|o| o[1]).sum::<f32>() / off.len() as f32,
        );
        for o in &mut off {
            o[0] -= mx;
            o[1] -= my;
        }
        let r = off.iter().map(|o| (o[0] * o[0] + o[1] * o[1]).sqrt()).fold(0.0, f32::max) + NODE_R;
        radii.push(r.max(NODE_R * 2.0));
        // rel drives the colour gradient, so it MUST come from where the node
        // actually ends up — not the pre-relaxation `xy`. Deriving it from the
        // final packed offsets is what makes neighbouring nodes share a shade.
        sec_rel.push(unit_box(&off));
        sec_off.push(off);
    }

    // Non-grid arrangement, NOT by category similarity: seed the blobs in a
    // sunflower spiral and relax so they pack into one rounded segregated mass.
    let centers = arrange_sections(&radii);

    let mut nodes = Vec::new();
    let mut sections = Vec::new();
    for (idx, sec) in order.iter().enumerate() {
        let items = &by_section[sec];
        let (ctr_x, ctr_y) = (centers[idx][0], centers[idx][1]);
        let color = color_for(sec);

        for (j, it) in items.iter().enumerate() {
            let off = sec_off[idx][j];
            nodes.push(Node {
                path: it.path.clone(),
                filename: it.filename.clone(),
                section: sec.clone(),
                confidence: it.confidence,
                x: ctr_x + off[0],
                y: ctr_y + off[1],
                color,
                rel_x: sec_rel[idx][j][0],
                rel_y: sec_rel[idx][j][1],
                section_id: section_id(sec),
                envelope: it.envelope.clone(),
                duration: it.duration,
                home_x: ctr_x + off[0],
                home_y: ctr_y + off[1],
                vx: 0.0,
                vy: 0.0,
            });
        }
        sections.push(SectionMeta {
            name: sec.clone(),
            count: items.len(),
            color,
            cx: ctr_x,
            cy: ctr_y,
        });
    }
    sections.sort_by(|a, b| b.count.cmp(&a.count));
    (nodes, sections)
}
